### ISSUE TITLE
About training view selection

### ISSUE THREAD

**Issue by zhanghaoyu816** [mvp18/sp2-360#1]
Thanks for your nice project. 
I want to select sparse training views in some complex scene such as mipnerf360, scannet or tanks&temples so that these views can cover most of the whole scene with less overlap between views. So could you please provide the code for data selection in your project? 
Thanks a lot.

**Comment by mvp18** [comment]
Hi @zhanghaoyu816,

Thanks for your interest in our work. I'll share the view selection code in this thread soon after some cleaning. Meanwhile, you can refer to the ReconFusion splits available [here](https://drive.google.com/drive/folders/10oT2_OQ9Sjh5wlfJQoGx2y7ZKYwpgNg5?usp=sharing) for mipnerf360 splits that maximize scene coverage, but cannot always register all input images to a single point cloud. These splits are more helpful if your 3D representation is NeRF-based and not point-based like 3dGS. 

Our splits have more overlap across views but at the cost of lower scene coverage.

Best,
mvp18

**Comment by zhanghaoyu816** [comment]
Thanks for your reply, I'm looking forward it.

**Comment by mvp18** [comment]
Hi @zhanghaoyu816, 

I have added code for our view-selection algorithm. Let me know if you have further questions or issues.

**Comment by zhanghaoyu816** [comment]
Thanks for your code.

**Comment by tmanh** [comment]
Hi, I have followed the view selection code. But, I cannot get the same selected views in the papers. The global maxima of the treehill and stump are different from what stated in the paper.

 Treehill:
![treehill_filter_9_views_trans0 1](https://github.com/user-attachments/assets/98c57998-b881-4814-a279-9883522f85b6)

Stump:
![stump_filter_18_views_trans0 1](https://github.com/user-attachments/assets/69d458a9-097f-4462-a4f8-3b5e32c2df7d)
